### ISSUE TITLE
Upgrade to 6.2.1 causes "WebDriver Error: Sauce could not start your job"

### ISSUE THREAD

**Issue by web-padawan** [saucelabs/node-saucelabs#129]
We have a failure in `@web/test-runner-saucelabs` apparently related to #124

```
  test-runner-saucelabs
    many
[Saucelabs] Setting up Sauce Connect proxy...
2021-11-01T07:55:26.668Z ERROR webdriver: Request failed with status 500 due to WebDriver Error: Sauce could not start your job. For more information on what happened, please visit https://app.eu-central-1.saucelabs.com/tests/29b2baead1cb4ba0b56c215a832a30e5
2021-11-01T07:55:26.670Z ERROR webdriver: WebDriver Error: Sauce could not start your job. For more information on what happened, please visit https://app.eu-central-1.saucelabs.com/tests/29b2baead1cb4ba0b56c215a832a30e5
    at getErrorFromResponseBody (/home/runner/work/web/web/node_modules/webdriver/build/utils.js:196:12)
    at NodeJSRequest._request (/home/runner/work/web/web/node_modules/webdriver/build/request/index.js:157:60)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async startWebDriverSession (/home/runner/work/web/web/node_modules/webdriver/build/utils.js:66:20)
    at async Function.newSession (/home/runner/work/web/web/node_modules/webdriver/build/index.js:58:45)
    at async Object.remote (/home/runner/work/web/web/node_modules/webdriverio/build/index.js:67:22)
    at async SauceLabsLauncher.createDriverManager (/home/runner/work/web/web/packages/test-runner-webdriver/dist/webdriverLauncher.js:84:28)
```

See the build here: https://github.com/modernweb-dev/web/runs/4065325874

At first it failed on `7.0.0` major bump https://github.com/modernweb-dev/web/pull/1729
But then I realised that even minor bump of `saucelabs` to 6.2.1 causes this.

@christian-bromann could you please give some pointers on what goes wrong here?

**Comment by christian-bromann** [comment]
@web-padawan it seems that the issue is that `tunnelIdentifier` got deprecated by the Sauce Connect team, the new property should be `tunnelName`. Can you try to update to the latest version and use `--tunnelName` as parameter?

**Comment by web-padawan** [comment]
Thank you for quick response, I will try it out. It's a pity that such breaking changes land in minor releases 😕

**Comment by christian-bromann** [comment]
I know. This was a mistake on our side. I am sorry! Our team wasn't aware of these breaking changes in SC as it was a minor bump in their version as well. We will test it more throughly next time.

**Comment by web-padawan** [comment]
No problem, this is a relatively small change and it's definitely fine to have it in 7.0.x release 👍 
Maybe it makes sense to revert it for 6.2.x and have a patch release to not affect users.

**Comment by web-padawan** [comment]
So I changed to use `tunnelName` https://github.com/modernweb-dev/web/pull/1729/commits/aec925f49e710ad8e7496ad29c3773321cce4b80 and now there is a different error 😱 

```
Backtrace:
	Ordinal0 [0x014C3AB3+2505395]
	Ordinal0 [0x0145AE41+2076225]
	Ordinal0 [0x01362498+1057944]
	Ordinal0 [0x0135F0A1+1044641]
	Ordinal0 [0x013552C2+1004226]
	Ordinal0 [0x01355EC2+1007298]
	Ordinal0 [0x0135550A+1004810]
	Ordinal0 [0x01354BC8+1002440]
	Ordinal0 [0x01353D5D+998749]
	Ordinal0 [0x01354016+999446]
	Ordinal0 [0x01363A6A+1063530]
	Ordinal0 [0x013B56ED+1398509]
	Ordinal0 [0x013A59F3+1333747]
	Ordinal0 [0x013B5168+1397096]
	Ordinal0 [0x013A58BB+1333435]
	Ordinal0 [0x013823E4+1188836]
	Ordinal0 [0x0138323F+1192511]
	GetHandleVerifier [0x0164CB36+1554566]
	GetHandleVerifier [0x016F4A0C+2242396]
	GetHandleVerifier [0x01550E0B+523099]
	GetHandleVerifier [0x0154FEB0+519168]
	Ordinal0 [0x014602FD+2097917]
	Ordinal0 [0x01464388+2114440]
	Ordinal0 [0x014644C2+2114754]
	Ordinal0 [0x0146E041+2154561]
	BaseThreadInitThunk [0x770C38F4+36]
	RtlUnicodeStringToInteger [0x778D5E13+595]
	RtlUnicodeStringToInteger [0x778D5DDE+542]
```

**Comment by christian-bromann** [comment]
> Maybe it makes sense to revert it for 6.2.x and have a patch release to not affect users.

Done.

> and now there is a different error 😱

I will check in with the team to see what this means, trying to reproduce it in Ubuntu 20.04.

**Comment by web-padawan** [comment]
For now, I put our 7.0.0 update on hold, so no pressure with this at all. Thank you for handling 6.x version 🙇‍♂️

**Comment by web-padawan** [comment]
@christian-bromann Hi, is there any update or an issue where this is tracked? The above error is still there.

**Comment by christian-bromann** [comment]
@web-padawan I left Sauce Labs and won't have the time to work on this in near future.

@diemol can you take over?

**Comment by web-padawan** [comment]
Oh, sorry to bother you. As I mentioned above, this isn't urgent. Here is [the most recent build](https://github.com/modernweb-dev/web/runs/4215943457?check_suite_focus=true).

**Comment by boneskull** [comment]
@web-padawan I can try to help with this.  The build you linked to is missing, however.

I think it'd be helpful to understand if this problem is Sauce-Connect-specific or `node-saucelabs`-specific.  I'll see if we have (or can implement) a debugging flag which will echo the `sc` command, so it may be possible to copy & paste the command and see its behavior outside of a `node-saucelabs` context.

**Comment by web-padawan** [comment]
Looks like the error is no longer reproducible with `7.2.0` version - here is a [fixed build](https://github.com/modernweb-dev/web/runs/6530087501). Closing the issue.
